name: file_copy
description: Package for copy files, directories, links. You can watch the copying process.
version: 1.0.4
repository: https://github.com/GlebBatykov/file_copy

environment:
  sdk: ">=2.12.0 <4.0.0"

topics:
  - file
  - directory
  - copy

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
